### PR TITLE
When using cuda, the model need to be copied to GPU

### PR DESCRIPTION
**Pull request by benwu232**

### CODE REVIEW

**Comment by benwu232** [comment]
Thanks for the wonderful code!

**Comment by ncullen93** [comment]
THANK YOU!

**Comment by benwu232** [comment]
I read the code again. Current modification copies the model to gpu in each batch. Unless the computation graph changes in each batch, this method is not so efficient. My idea is add another trigger, say dyna_graph, to control this:
if dyna_graph == 0
    the model will be copied to gpu before the epoch loop
elif dyna_graph == 1
    the model will be copied to gpu in each epoch
else
    the model will be copied to gpu in each batch

or you can add a new callback to update the computation graph. This needs no modification for current function interface.

What do you think?

**Comment by benwu232** [comment]
I suggest to add a new callback to handle when to update dynamic computation graph and using cuda_device there to decide if copying the updated model to gpu.

**Pull request merged**
